version: '3.8'
services:
  app:
    image: spendwise-bo:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spendwise-bo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/spendWise
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 111111
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: spendWise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111111
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
